# Create a Namespace
# kubectl create ns mynamespace
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace
  # can have labels

---
# Create a Pod with NGINX image in the created Namespace
# kubectl run nginx -n mynamespace --image nginx
# To generate below YAML automatically: kubectl run nginx -n mynamespace --image nginx --dry-run=client -o yaml > nginx-pod.yaml
# Create Pod from YAML: kubectl create -f nginx-pod.yaml
# Use --restart=Never to prevent restart if the Pod already exists and is running
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: mynamespace
  # can have labels and annotations
spec:
  containers:
  - name: nginx
    image: nginx

---
# Create a Pod with container commands, with kubectl and YAML
# kubectl run busybox --image busybox --command -- env
# To see log output, run kubectl logs busybox after kubectl run, or use -it --rm in kubectl run to see the output and clean up the Pod upon exit

# With YAML: kubectl run busybox --image=busybox --dry-run=client -o yaml --command -- env > busybox-pod.yaml
# Create Pod from generated YAML: kubectl apply -f busybox-pod.yaml
# See the output: kubectl logs busybox

apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox
  - command:
    - env